CREATE MASTER KEY ENCRYPTION
	BY PASSWORD = 'RbYZ3*iLEogXXWDf8mwM';

CREATE DATABASE SCOPED CREDENTIAL [SqlCredsMI] 
WITH IDENTITY='Managed Identity';

CREATE EXTERNAL DATA SOURCE DataLakeMI WITH ( 
    LOCATION = 'https://module6synapsedl.dfs.core.windows.net' 
    , CREDENTIAL = SqlCredsMI
);

CREATE EXTERNAL FILE FORMAT DeltaLakeFormat WITH (  FORMAT_TYPE = DELTA );
